name: Slither Static Analysis
on:
  pull_request:
    branches: [ "main" ]
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crytic/slither-action@v0.2.0
        with:
          slither-args: "--no-fail-pedantic --exclude-low --exclude naming-convention,unused-return,uninitialized-local-variables,missing-inheritance,low-level-calls,assembly,solc-version,pragma"
          fail-on: medium
